import type { GearFamilyRule } from '../types.ts';

/**
 * Equipment families. `base` is a class 1 item with neutral maker traits. For each class and maker
 * the generator applies `drift` and the maker's traits to the secondary stats, then solves the
 * primary stat (gun damage, shield capacity, engine thrust, ...) so the item hits its class budget.
 *
 * Guns share one budget (every gun family's class 1 matches the pulse cannon), and so do shields
 * (they match the balanced shield). The Halden class 1 pulse cannon, balanced shield, seeker
 * launcher, engine, thruster and power plant are the original starting fittings.
 */
export const GEAR_FAMILIES: readonly GearFamilyRule[] = [
  // ------------------------------------------------------------ guns (one per gun slot)
  {
    id: 'pulse',
    slot: 'gun',
    noun: 'pulse cannon',
    damageType: 'energy',
    base: { damage: 9, shotsPerSecond: 2.75, projectileSpeed: 760, range: 950, energyPerShot: 5 },
    drift: { projectileSpeed: 1.03, range: 1.02, energyPerShot: 1.12 },
    growth: 1.28,
    minTierStep: 0.18,
    basePrice: 190,
    priceGrowth: 1.6,
    flavour: 'Rapid energy bolts; the all-rounder.',
  },
  {
    id: 'mass-driver',
    slot: 'gun',
    noun: 'mass driver',
    damageType: 'kinetic',
    base: { damage: 15, shotsPerSecond: 1.1, projectileSpeed: 1050, range: 1150, energyPerShot: 9 },
    drift: { projectileSpeed: 1.03, range: 1.02, energyPerShot: 1.12 },
    growth: 1.28,
    minTierStep: 0.18,
    basePrice: 190,
    priceGrowth: 1.6,
    flavour: 'Fast magnetic slugs, slow to cycle and hard on hulls.',
  },
  {
    id: 'plasma',
    slot: 'gun',
    noun: 'plasma cannon',
    damageType: 'plasma',
    base: { damage: 30, shotsPerSecond: 0.8, projectileSpeed: 560, range: 850, energyPerShot: 14 },
    drift: { projectileSpeed: 1.03, range: 1.02, energyPerShot: 1.12 },
    growth: 1.28,
    minTierStep: 0.18,
    basePrice: 190,
    priceGrowth: 1.6,
    flavour: 'Heavy, slow plasma bolts that burn through diffusers.',
  },
  {
    id: 'ion',
    slot: 'gun',
    noun: 'ion disruptor',
    damageType: 'ion',
    base: { damage: 13, shotsPerSecond: 2.2, projectileSpeed: 850, range: 900, energyPerShot: 6 },
    drift: { projectileSpeed: 1.03, range: 1.02, energyPerShot: 1.12 },
    growth: 1.28,
    minTierStep: 0.18,
    basePrice: 190,
    priceGrowth: 1.6,
    flavour: 'Collapses shields fast but barely scratches a hull; pair it with another gun.',
  },
  // ------------------------------------------------------------ shields
  {
    id: 'shield-balanced',
    slot: 'shield',
    noun: 'shield',
    shieldType: 'balanced',
    base: { capacity: 60, regenPerSecond: 6, regenDelay: 3 },
    drift: { regenDelay: 0.96 },
    growth: 1.3,
    minTierStep: 0.18,
    basePrice: 220,
    priceGrowth: 1.6,
    flavour: 'An even field with no weak spots.',
  },
  {
    id: 'shield-deflector',
    slot: 'shield',
    noun: 'deflector shield',
    shieldType: 'deflector',
    base: { capacity: 66, regenPerSecond: 5.5, regenDelay: 3.2 },
    drift: { regenDelay: 0.96 },
    growth: 1.3,
    minTierStep: 0.18,
    basePrice: 220,
    priceGrowth: 1.6,
    flavour: 'A hard field that sheds slugs.',
  },
  {
    id: 'shield-diffuser',
    slot: 'shield',
    noun: 'diffuser shield',
    shieldType: 'diffuser',
    base: { capacity: 56, regenPerSecond: 7, regenDelay: 2.8 },
    drift: { regenDelay: 0.96 },
    growth: 1.3,
    minTierStep: 0.18,
    basePrice: 220,
    priceGrowth: 1.6,
    flavour: 'Spreads energy hits thin and recovers quickly.',
  },
  // ------------------------------------------------------------ launchers
  {
    id: 'rocket-pod',
    slot: 'launcher',
    noun: 'rocket pod',
    kind: 'rocket',
    base: { damage: 40, speed: 420, turnRate: 0, lifetime: 5, lockTime: 0, maxAmmo: 12, ammoPrice: 12 },
    drift: { speed: 1.03, turnRate: 1, ammoPrice: 1.3 },
    growth: 1.25,
    minTierStep: 0.15,
    basePrice: 140,
    priceGrowth: 1.5,
    flavour: 'Unguided rockets; aim well, reload cheaply.',
  },
  {
    id: 'seeker',
    slot: 'launcher',
    noun: 'seeker launcher',
    kind: 'seeker',
    base: { damage: 55, speed: 280, turnRate: 2.6, lifetime: 9, lockTime: 0.8, maxAmmo: 6, ammoPrice: 35 },
    drift: { speed: 1.03, turnRate: 1.04, ammoPrice: 1.3 },
    growth: 1.25,
    minTierStep: 0.15,
    basePrice: 150,
    priceGrowth: 1.5,
    flavour: 'Homing missiles that lock on and give chase.',
  },
  {
    id: 'torpedo',
    slot: 'launcher',
    noun: 'torpedo tube',
    kind: 'torpedo',
    base: { damage: 180, speed: 200, turnRate: 1, lifetime: 14, lockTime: 1.6, maxAmmo: 2, ammoPrice: 120 },
    drift: { speed: 1.03, turnRate: 1.04, ammoPrice: 1.3 },
    growth: 1.25,
    minTierStep: 0.15,
    basePrice: 240,
    priceGrowth: 1.5,
    flavour: 'Slow, heavy torpedoes for big targets.',
  },
  // ------------------------------------------------------------ drive and power
  {
    id: 'engine',
    slot: 'engine',
    noun: 'cruise engine',
    base: { cruiseSpeed: 620, cruiseChargeTime: 1.8, thrust: 1 },
    drift: { cruiseSpeed: 1.05, cruiseChargeTime: 0.95 },
    growth: 1.08,
    minTierStep: 0.05,
    basePrice: 160,
    priceGrowth: 1.5,
    flavour: 'Sets cruise speed and acceleration.',
  },
  {
    id: 'thruster',
    slot: 'thruster',
    noun: 'thruster',
    base: { boostSpeed: 95, boostDrain: 28 },
    growth: 1.08,
    minTierStep: 0.05,
    basePrice: 110,
    priceGrowth: 1.5,
    flavour: 'Afterburner for combat boosts.',
  },
  {
    id: 'power',
    slot: 'power',
    noun: 'power plant',
    base: { energyMax: 100, energyRegen: 20 },
    growth: 1.2,
    minTierStep: 0.1,
    basePrice: 150,
    priceGrowth: 1.55,
    flavour: 'Feeds the guns and the boost.',
  },
  // ------------------------------------------------------------ utility
  {
    id: 'armor',
    slot: 'utility',
    noun: 'armour plating',
    kind: 'armor',
    base: { amount: 25, penalty: 0.05 },
    growth: 1.3,
    minTierStep: 0.15,
    basePrice: 130,
    priceGrowth: 1.5,
    flavour: 'Bolt-on hull plates.',
  },
  {
    id: 'cargo-pod',
    slot: 'utility',
    noun: 'cargo pod',
    kind: 'cargo-pod',
    base: { amount: 8, penalty: 0.04 },
    growth: 1.3,
    minTierStep: 0.15,
    basePrice: 140,
    priceGrowth: 1.5,
    flavour: 'An external hold.',
  },
  {
    id: 'scanner',
    slot: 'utility',
    noun: 'scanner',
    kind: 'scanner',
    base: { amount: 1.25, penalty: 0 },
    growth: 1.12,
    minTierStep: 0.08,
    basePrice: 120,
    priceGrowth: 1.5,
    flavour: 'Longer-range sensors for scans and targeting.',
  },
  {
    id: 'tractor',
    slot: 'utility',
    noun: 'tractor beam',
    kind: 'tractor',
    // Every ship pulls in loose cargo from 350 m on its own; a beam reaches further.
    base: { amount: 500, penalty: 0 },
    growth: 1.2,
    minTierStep: 0.1,
    basePrice: 90,
    priceGrowth: 1.5,
    flavour: 'Reels in loose cargo and salvage.',
  },
  {
    id: 'jump-drive',
    slot: 'utility',
    noun: 'long-range jump drive',
    kind: 'jump-drive',
    // Reach in light-years: frontier lanes (docs/PROCGEN.md §7.7) need a drive that reaches them.
    base: { amount: 11, penalty: 0 },
    growth: 1.06,
    minTierStep: 0.04,
    basePrice: 2_400,
    priceGrowth: 1.45,
    flavour: 'Reaches the unbeaconed lanes of the frontier.',
  },
  {
    id: 'mining-laser',
    slot: 'utility',
    noun: 'mining laser',
    kind: 'mining-laser',
    // Units of ore or ice cut from a rock per minute of beam.
    base: { amount: 6, penalty: 0 },
    growth: 1.3,
    minTierStep: 0.15,
    basePrice: 220,
    priceGrowth: 1.5,
    flavour: 'Cuts ore and ice from rock.',
  },
  {
    id: 'prospector',
    slot: 'utility',
    noun: 'prospecting scanner',
    kind: 'prospector',
    // Yield: a rock gives this many times what it would to an unaided cut.
    base: { amount: 1.2, penalty: 0 },
    growth: 1.1,
    minTierStep: 0.05,
    basePrice: 160,
    priceGrowth: 1.5,
    flavour: 'Reads a rock’s seams before you cut.',
  },
];
