import type { ManufacturerRule } from '../types.ts';

/**
 * Ship and equipment makers (all fiction). Each has tendencies, a product range and a naming
 * grammar, so a name tells you who built it. Traits are trade-offs: the generator keeps every item
 * inside its power budget (docs/PROCGEN.md §4.1).
 */
export const MANUFACTURERS: readonly ManufacturerRule[] = [
  {
    id: 'halden',
    name: 'Halden Orbital Works',
    short: 'Halden',
    homeSystem: 'sol',
    homeLocation: 'earth-port',
    factionId: 'sta',
    blurb:
      'Halden builds the ships most pilots learn on: forgiving, easy to maintain and cheap to run. Its yards hang off the Halcyon Ring above Earth.',
    // The reference maker: neutral everywhere.
    tendency: 'Balanced and forgiving',
    traits: {},
    ships: { courier: [1, 2, 3], 'light-fighter': [1, 2], freighter: [1, 2] },
    gear: {
      pulse: [1, 2, 3],
      'shield-balanced': [1, 2, 3],
      seeker: [1, 2],
      engine: [1, 2, 3],
      thruster: [1, 2, 3],
      power: [1, 2, 3],
      'cargo-pod': [1, 2],
      scanner: [1],
      tractor: [1],
    },
    names: {
      // Seabirds.
      ships: ['Petrel', 'Tern', 'Gannet', 'Shearwater', 'Fulmar', 'Kittiwake', 'Skua', 'Albatross'],
      gear: {
        pulse: 'Kestrel',
        'shield-balanced': 'Aegis',
        seeker: 'Merlin',
        engine: 'Tailwind',
        thruster: 'Updraft',
        power: 'Lantern',
        'cargo-pod': 'Seahold',
        scanner: 'Lookout',
        tractor: 'Gleaner',
      },
    },
    style: {
      palette: { hull: '#e8edf2', panel: '#9fb3c8', accent: '#3a7bd5', glow: '#7fd4ff' },
      silhouette: 'wedge',
      wings: 'swept',
      greeble: 0.3,
      note: 'Clean white hulls with blue trim and swept wings; friendly and civilian.',
    },
  },
  {
    id: 'ares',
    name: 'Ares Foundry',
    short: 'Ares',
    homeSystem: 'sol',
    homeLocation: 'mars-depot',
    factionId: 'sta',
    blurb: 'Ares Foundry forges armoured hulls in the Deimos yards. Its ships are slow to turn, but they take a beating and hit back hard.',
    tendency: 'Armoured and hard-hitting, slow to turn',
    traits: { hull: 1.15, agility: 0.9, speed: 0.95, fireRate: 0.85, velocity: 1.08, efficiency: 0.95, shieldRegen: 0.85, price: 1.05 },
    ships: { 'heavy-fighter': [1, 2, 3], gunship: [2, 3], freighter: [2] },
    gear: {
      'mass-driver': [1, 2, 3, 4, 5],
      'shield-deflector': [1, 2, 3, 4, 5],
      plasma: [2, 3, 4],
      'rocket-pod': [1, 2, 3],
      torpedo: [2, 3, 4],
      armor: [1, 2, 3],
      power: [1, 2, 3, 4],
    },
    names: {
      // Forge tools and fortifications.
      ships: ['Anvil', 'Rampart', 'Mattock', 'Crucible', 'Palisade', 'Redoubt', 'Barbican', 'Casemate'],
      gear: {
        'mass-driver': 'Drophammer',
        'shield-deflector': 'Bulwark',
        plasma: 'Bellows',
        'rocket-pod': 'Rivet',
        torpedo: 'Sledge',
        armor: 'Ironclad',
        power: 'Furnace',
      },
    },
    style: {
      palette: { hull: '#5b5f66', panel: '#3d4046', accent: '#d9822b', glow: '#ffb35c' },
      silhouette: 'block',
      wings: 'straight',
      greeble: 0.8,
      note: 'Slab-sided gunmetal hulls, heavy plating, stubby straight wings, orange hazard trim.',
    },
  },
  {
    id: 'toliman',
    name: 'Toliman Cooperative Yards',
    short: 'Toliman',
    homeSystem: 'alpha-centauri',
    homeLocation: 'meridian-outpost',
    factionId: 'frontier',
    blurb: 'The Cooperative Yards build for the frontier: roomy holds, frugal power systems and long-range survey gear.',
    tendency: 'Roomy and frugal with power',
    traits: { cargo: 1.15, power: 1.05, hull: 0.95, efficiency: 1.12, shieldRegen: 1.1, cruise: 0.97, price: 0.97 },
    ships: { surveyor: [1, 2, 3], freighter: [1, 2, 3], 'light-fighter': [1] },
    gear: {
      pulse: [1, 2],
      'shield-diffuser': [1, 2, 3],
      engine: [1, 2, 3],
      power: [1, 2, 3],
      'cargo-pod': [1, 2, 3],
      scanner: [1, 2, 3],
      tractor: [1, 2, 3],
    },
    names: {
      // Trees.
      ships: ['Juniper', 'Larch', 'Rowan', 'Aspen', 'Cedar', 'Hawthorn', 'Alder', 'Linden'],
      gear: {
        pulse: 'Thorn',
        'shield-diffuser': 'Canopy',
        engine: 'Seedwind',
        power: 'Sapwell',
        'cargo-pod': 'Granary',
        scanner: 'Taproot',
        tractor: 'Tendril',
      },
    },
    style: {
      palette: { hull: '#c9b98f', panel: '#7d8a5c', accent: '#e0c341', glow: '#b6ff8a' },
      silhouette: 'pod',
      wings: 'twin-boom',
      greeble: 0.5,
      note: 'Rounded pods on twin booms in sand and olive work paint; practical and repairable.',
    },
  },
  {
    id: 'horizon',
    name: 'Horizon Dynamics',
    short: 'Horizon',
    homeSystem: 'sirius',
    homeLocation: 'sirius-platform',
    factionId: 'frontier',
    blurb: 'Horizon Dynamics designs fast, power-hungry ships and precision equipment in the Sirius labs. Light armour, high prices, superb performance.',
    tendency: 'Fast and agile, lightly armoured',
    traits: {
      hull: 0.88,
      agility: 1.08,
      speed: 1.08,
      power: 1.12,
      fireRate: 1.12,
      velocity: 1.05,
      efficiency: 1.05,
      shieldRegen: 1.15,
      cruise: 1.06,
      price: 1.15,
    },
    ships: { 'light-fighter': [2, 3], 'heavy-fighter': [2, 3], courier: [2, 3], surveyor: [2, 3] },
    gear: {
      pulse: [2, 3, 4, 5],
      'shield-diffuser': [2, 3, 4, 5],
      ion: [2, 3, 4, 5],
      seeker: [2, 3, 4],
      engine: [2, 3, 4],
      thruster: [2, 3, 4, 5],
      power: [2, 3, 4, 5],
      scanner: [3, 4],
    },
    names: {
      // Optics and orbital terms.
      ships: ['Parallax', 'Zenith', 'Solstice', 'Aphelion', 'Perihelion', 'Umbra', 'Penumbra', 'Azimuth', 'Nadir', 'Equinox'],
      gear: {
        pulse: 'Lumen',
        'shield-diffuser': 'Prism',
        ion: 'Eclipse',
        seeker: 'Glint',
        engine: 'Apogee',
        thruster: 'Flare',
        power: 'Flux',
        scanner: 'Iris',
      },
    },
    style: {
      palette: { hull: '#1d2330', panel: '#c7ccd6', accent: '#9d7bff', glow: '#d0b8ff' },
      silhouette: 'blade',
      wings: 'delta',
      greeble: 0.15,
      note: 'Long dark blade hulls with mirrored silver panels, violet light strips and delta wings.',
    },
  },
  {
    id: 'eridani',
    name: 'Eridani Shipwrights',
    short: 'Eridani',
    homeSystem: 'epsilon-eridani',
    homeLocation: 'eridani-hub',
    factionId: 'frontier',
    blurb: 'Eridani Shipwrights weld haulers for the mining belts: big holds, tough frames and prices a hauler can afford.',
    tendency: 'Roomy, tough and cheap',
    traits: { cargo: 1.2, speed: 0.95, velocity: 0.95, shieldRegen: 0.95, price: 0.9 },
    ships: { freighter: [1, 2, 3], courier: [1, 2], gunship: [2, 3] },
    gear: {
      'mass-driver': [1, 2, 3],
      'shield-balanced': [1, 2, 3, 4],
      engine: [1, 2],
      'cargo-pod': [1, 2, 3, 4],
      armor: [1, 2],
      tractor: [1, 2],
    },
    names: {
      // Rivers and tides.
      ships: ['Tidewater', 'Estuary', 'Shoal', 'Confluence', 'Longshore', 'Riptide', 'Headwater', 'Meander', 'Oxbow'],
      gear: {
        'mass-driver': 'Millrace',
        'shield-balanced': 'Levee',
        engine: 'Current',
        'cargo-pod': 'Floodgate',
        armor: 'Breakwater',
        tractor: 'Undertow',
      },
    },
    style: {
      palette: { hull: '#3f6f78', panel: '#a9b7b2', accent: '#f2f0e6', glow: '#8ff0e0' },
      silhouette: 'ring',
      wings: 'none',
      greeble: 0.6,
      note: 'Weathered teal haulers built around a spine and cargo ring; few or no wings.',
    },
  },
  {
    id: 'wake',
    name: 'Wake Salvage',
    short: 'Wake',
    homeSystem: 'barnard',
    // Pirate dens are not open to the player yet: raiders fly these.
    homeLocation: null,
    factionId: 'hollow-wake',
    blurb: 'What the Hollow Wake calls its scrapyards. Stolen hulls rebuilt for ambushes: quick, vicious and thin-skinned.',
    tendency: 'Quick and vicious, thin-skinned',
    traits: { hull: 0.85, agility: 1.1, speed: 1.05, fireRate: 1.1, efficiency: 0.88, price: 0.8 },
    ships: { 'light-fighter': [1, 2], 'heavy-fighter': [1, 2] },
    gear: {
      plasma: [1, 2, 3],
      'shield-deflector': [1, 2],
      'mass-driver': [1, 2],
      ion: [1, 2],
      'rocket-pod': [1, 2, 3],
      torpedo: [2],
    },
    names: {
      // Predators and ash.
      ships: ['Rook', 'Jackal', 'Marten', 'Cinder', 'Ember', 'Hyena', 'Snare', 'Barb'],
      gear: {
        plasma: 'Scorch',
        'shield-deflector': 'Scab',
        'mass-driver': 'Fang',
        ion: 'Static',
        'rocket-pod': 'Spite',
        torpedo: 'Grudge',
      },
    },
    style: {
      palette: { hull: '#2b2624', panel: '#6b3a2e', accent: '#ff5a3c', glow: '#ff8a5c' },
      silhouette: 'splice',
      wings: 'asymmetric',
      greeble: 0.9,
      note: 'Hulls spliced from mismatched parts; soot and rust with red slashes; asymmetric fins.',
    },
  },
];
